
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

namespace Web_App.AppCode.Helper.Language
{
    public static partial class LanguageHelper
    {
        public static string Accion
        {
            get { return GetString("Accion"); }
        }
   
        public static string Acciones
        {
            get { return GetString("Acciones"); }
        }
   
        public static string Aceptar
        {
            get { return GetString("Aceptar"); }
        }
   
        public static string ActivarDesactivar
        {
            get { return GetString("ActivarDesactivar"); }
        }
   
        public static string AdquirirMembresia
        {
            get { return GetString("AdquirirMembresia"); }
        }
   
        public static string Bitacora
        {
            get { return GetString("Bitacora"); }
        }
   
        public static string BitacoraDescripcion
        {
            get { return GetString("BitacoraDescripcion"); }
        }
   
        public static string Buscar
        {
            get { return GetString("Buscar"); }
        }
   
        public static string Bye
        {
            get { return GetString("Bye"); }
        }
   
        public static string Cancelar
        {
            get { return GetString("Cancelar"); }
        }
   
        public static string Canton
        {
            get { return GetString("Canton"); }
        }
   
        public static string Cedula
        {
            get { return GetString("Cedula"); }
        }
   
        public static string CedulaJuridica
        {
            get { return GetString("CedulaJuridica"); }
        }
   
        public static string ComenzarATrabajarEnSusProyectos
        {
            get { return GetString("ComenzarATrabajarEnSusProyectos"); }
        }
   
        public static string ComienceAAprender
        {
            get { return GetString("ComienceAAprender"); }
        }
   
        public static string ComienceAConstruir
        {
            get { return GetString("ComienceAConstruir"); }
        }
   
        public static string ComienceADisenar
        {
            get { return GetString("ComienceADisenar"); }
        }
   
        public static string ComprarAhora
        {
            get { return GetString("ComprarAhora"); }
        }
   
        public static string Confianza
        {
            get { return GetString("Confianza"); }
        }
   
        public static string ConfianzaDescripcion
        {
            get { return GetString("ConfianzaDescripcion"); }
        }
   
        public static string ConfirmacionEliminar
        {
            get { return GetString("ConfirmacionEliminar"); }
        }
   
        public static string ConfirmacionEstado
        {
            get { return GetString("ConfirmacionEstado"); }
        }
   
        public static string Conocenos
        {
            get { return GetString("Conocenos"); }
        }
   
        public static string ConozcaMaster
        {
            get { return GetString("ConozcaMaster"); }
        }
   
        public static string ContacteALosMejores
        {
            get { return GetString("ContacteALosMejores"); }
        }
   
        public static string ConvertirseEnMaster
        {
            get { return GetString("ConvertirseEnMaster"); }
        }
   
        public static string CorreoElectronico
        {
            get { return GetString("CorreoElectronico"); }
        }
   
        public static string Crear
        {
            get { return GetString("Crear"); }
        }
   
        public static string CumpleConElFormato
        {
            get { return GetString("CumpleConElFormato"); }
        }
   
        public static string Descripcion
        {
            get { return GetString("Descripcion"); }
        }
   
        public static string DescripcionMasterLanding
        {
            get { return GetString("DescripcionMasterLanding"); }
        }
   
        public static string DireccionExacta
        {
            get { return GetString("DireccionExacta"); }
        }
   
        public static string Distrito
        {
            get { return GetString("Distrito"); }
        }
   
        public static string Documentos
        {
            get { return GetString("Documentos"); }
        }
   
        public static string DocumentosDescripcion
        {
            get { return GetString("DocumentosDescripcion"); }
        }
   
        public static string Editar
        {
            get { return GetString("Editar"); }
        }
   
        public static string ElaboradoPor
        {
            get { return GetString("ElaboradoPor"); }
        }
   
        public static string Eliminar
        {
            get { return GetString("Eliminar"); }
        }
   
        public static string EncontrarMejoresProfesionales
        {
            get { return GetString("EncontrarMejoresProfesionales"); }
        }
   
        public static string Entidad
        {
            get { return GetString("Entidad"); }
        }
   
        public static string Estado
        {
            get { return GetString("Estado"); }
        }
   
        public static string Expertos
        {
            get { return GetString("Expertos"); }
        }
   
        public static string ExpertosDescripcion
        {
            get { return GetString("ExpertosDescripcion"); }
        }
   
        public static string ExtenderMembresia
        {
            get { return GetString("ExtenderMembresia"); }
        }
   
        public static string Fecha
        {
            get { return GetString("Fecha"); }
        }
   
        public static string FechaCreacion
        {
            get { return GetString("FechaCreacion"); }
        }
   
        public static string FechaNacimiento
        {
            get { return GetString("FechaNacimiento"); }
        }
   
        public static string Genero
        {
            get { return GetString("Genero"); }
        }
   
        public static string Guardar
        {
            get { return GetString("Guardar"); }
        }
   
        public static string Hola
        {
            get { return GetString("Hola"); }
        }
   
        public static string ID
        {
            get { return GetString("ID"); }
        }
   
        public static string Identificacion
        {
            get { return GetString("Identificacion"); }
        }
   
        public static string Identificador
        {
            get { return GetString("Identificador"); }
        }
   
        public static string IDPropietario
        {
            get { return GetString("IDPropietario"); }
        }
   
        public static string IDUsuario
        {
            get { return GetString("IDUsuario"); }
        }
   
        public static string ImpulsarNegocio
        {
            get { return GetString("ImpulsarNegocio"); }
        }
   
        public static string IngresarTextoCrear
        {
            get { return GetString("IngresarTextoCrear"); }
        }
   
        public static string IngresarTextoEditar
        {
            get { return GetString("IngresarTextoEditar"); }
        }
   
        public static string Inicio
        {
            get { return GetString("Inicio"); }
        }
   
        public static string InicioSesion
        {
            get { return GetString("InicioSesion"); }
        }
   
        public static string InscripcionAnual
        {
            get { return GetString("InscripcionAnual"); }
        }
   
        public static string InscripcionAnualDescripcion
        {
            get { return GetString("InscripcionAnualDescripcion"); }
        }
   
        public static string LenguajeDelSistema
        {
            get { return GetString("LenguajeDelSistema"); }
        }
   
        public static string MantenimientoTiposTrabajoDescripcion
        {
            get { return GetString("MantenimientoTiposTrabajoDescripcion"); }
        }
   
        public static string MejorarMembresia
        {
            get { return GetString("MejorarMembresia"); }
        }
   
        public static string Membresia
        {
            get { return GetString("Membresia"); }
        }
   
        public static string MembresiaEstandar
        {
            get { return GetString("MembresiaEstandar"); }
        }
   
        public static string MembresiaEstandarDescripcion
        {
            get { return GetString("MembresiaEstandarDescripcion"); }
        }
   
        public static string MembresiaPremium
        {
            get { return GetString("MembresiaPremium"); }
        }
   
        public static string MembresiaPremiumDescripcion
        {
            get { return GetString("MembresiaPremiumDescripcion"); }
        }
   
        public static string Membresias
        {
            get { return GetString("Membresias"); }
        }
   
        public static string MembresiasDescripcion
        {
            get { return GetString("MembresiasDescripcion"); }
        }
   
        public static string MonedaParaUsarEnElSistema
        {
            get { return GetString("MonedaParaUsarEnElSistema"); }
        }
   
        public static string NoCumpleConElFormato
        {
            get { return GetString("NoCumpleConElFormato"); }
        }
   
        public static string Nombre
        {
            get { return GetString("Nombre"); }
        }
   
        public static string NombreComercial
        {
            get { return GetString("NombreComercial"); }
        }
   
        public static string PaisDeNacimiento
        {
            get { return GetString("PaisDeNacimiento"); }
        }
   
        public static string Pasaporte
        {
            get { return GetString("Pasaporte"); }
        }
   
        public static string PorcentajeComisionPorTrabajo
        {
            get { return GetString("PorcentajeComisionPorTrabajo"); }
        }
   
        public static string PrimerApellido
        {
            get { return GetString("PrimerApellido"); }
        }
   
        public static string Productos
        {
            get { return GetString("Productos"); }
        }
   
        public static string PromocioneSuTrabajo
        {
            get { return GetString("PromocioneSuTrabajo"); }
        }
   
        public static string PromocioneSuTrabajoDescripcion
        {
            get { return GetString("PromocioneSuTrabajoDescripcion"); }
        }
   
        public static string Provincia
        {
            get { return GetString("Provincia"); }
        }
   
        public static string RazonSocial
        {
            get { return GetString("RazonSocial"); }
        }
   
        public static string Rechazar
        {
            get { return GetString("Rechazar"); }
        }
   
        public static string RecibaSusGanancias
        {
            get { return GetString("RecibaSusGanancias"); }
        }
   
        public static string RecibaSusGananciasDescripcion
        {
            get { return GetString("RecibaSusGananciasDescripcion"); }
        }
   
        public static string RegistreseAhora
        {
            get { return GetString("RegistreseAhora"); }
        }
   
        public static string RegistreseSinNingunCostoAdicional
        {
            get { return GetString("RegistreseSinNingunCostoAdicional"); }
        }
   
        public static string Residente
        {
            get { return GetString("Residente"); }
        }
   
        public static string Rol
        {
            get { return GetString("Rol"); }
        }
   
        public static string Saludo
        {
            get { return GetString("Saludo"); }
        }
   
        public static string SeaUnMaster
        {
            get { return GetString("SeaUnMaster"); }
        }
   
        public static string SegundoApellido
        {
            get { return GetString("SegundoApellido"); }
        }
   
        public static string Seguridad
        {
            get { return GetString("Seguridad"); }
        }
   
        public static string SeguridadDescripcion
        {
            get { return GetString("SeguridadDescripcion"); }
        }
   
        public static string SeleccioneUnaOpcion
        {
            get { return GetString("SeleccioneUnaOpcion"); }
        }
   
        public static string Telefono
        {
            get { return GetString("Telefono"); }
        }
   
        public static string TieneEmpresa
        {
            get { return GetString("TieneEmpresa"); }
        }
   
        public static string Tipo
        {
            get { return GetString("Tipo"); }
        }
   
        public static string TiposTrabajo
        {
            get { return GetString("TiposTrabajo"); }
        }
   
        public static string Titulo
        {
            get { return GetString("Titulo"); }
        }
   
        public static string TrabajeConExpertos
        {
            get { return GetString("TrabajeConExpertos"); }
        }
   
        public static string URL
        {
            get { return GetString("URL"); }
        }
   
        public static string VerboHTTP
        {
            get { return GetString("VerboHTTP"); }
        }
    }
}
